services:
  - type: web
    name: eroth-dashboard
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "22.16.0"
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_ALBION_SERVER
        value: americas
      - key: NEXT_PUBLIC_USE_LIVE_API
        value: "true"
      - key: NEXT_PUBLIC_EROTH_GUILD_ID
        value: "_ETEQ8jSQsyE-nFMXdqLGA"
